# Étape 1 : Construction de l'image avec les variables d'environnement injectées
FROM node:20.15.1-alpine as builder

# Définit le répertoire de travail
WORKDIR /app

# Copie les fichiers package pour installer les dépendances
COPY package.json package-lock.json ./

# Installe les dépendances
RUN npm install

# Copie le reste des fichiers de l'application
COPY . .

ARG NEXT_PUBLIC_API_BAN_URL
ARG NEXT_PUBLIC_BAL_ADMIN_API_URL
ARG NEXT_PUBLIC_API_GEO_URL
ARG NEXT_PUBLIC_ADRESSE_URL
ARG NEXT_PUBLIC_DATAGOUV_URL
ARG NEXT_PUBLIC_API_DEPOT_URL
ARG NEXT_PUBLIC_API_ETABLISSEMENTS_PUBLIC
ARG NEXT_PUBLIC_BAL_API_URL
ARG NEXT_PUBLIC_GHOST_URL
ARG NEXT_PUBLIC_GHOST_URL_IMAGES_SOURCE
ARG NEXT_PUBLIC_GHOST_KEY
ARG NEXT_PUBLIC_MATOMO_URL
ARG NEXT_PUBLIC_MATOMO_SITE_ID
ARG NEXT_PUBLIC_MOISSONNEUR_BAL_API_URL
ARG NEXT_PUBLIC_API_SIGNALEMENT

# Les variables d'environnement sont exportées avant le build
ENV NEXT_PUBLIC_API_BAN_URL=${NEXT_PUBLIC_API_BAN_URL}
ENV NEXT_PUBLIC_BAL_ADMIN_API_URL=${NEXT_PUBLIC_BAL_ADMIN_API_URL}
ENV NEXT_PUBLIC_API_GEO_URL=${NEXT_PUBLIC_API_GEO_URL}
ENV NEXT_PUBLIC_ADRESSE_URL=${NEXT_PUBLIC_ADRESSE_URL}
ENV NEXT_PUBLIC_DATAGOUV_URL=${NEXT_PUBLIC_DATAGOUV_URL}
ENV NEXT_PUBLIC_API_DEPOT_URL=${NEXT_PUBLIC_API_DEPOT_URL}
ENV NEXT_PUBLIC_API_ETABLISSEMENTS_PUBLIC=${NEXT_PUBLIC_API_ETABLISSEMENTS_PUBLIC}
ENV NEXT_PUBLIC_BAL_API_URL=${NEXT_PUBLIC_BAL_API_URL}
ENV NEXT_PUBLIC_GHOST_URL=${NEXT_PUBLIC_GHOST_URL}
ENV NEXT_PUBLIC_GHOST_URL_IMAGES_SOURCE=${NEXT_PUBLIC_GHOST_URL_IMAGES_SOURCE}
ENV NEXT_PUBLIC_GHOST_KEY=${NEXT_PUBLIC_GHOST_KEY}
ENV NEXT_PUBLIC_MATOMO_URL=${NEXT_PUBLIC_MATOMO_URL}
ENV NEXT_PUBLIC_MATOMO_SITE_ID=${NEXT_PUBLIC_MATOMO_SITE_ID}
ENV NEXT_PUBLIC_MOISSONNEUR_BAL_API_URL=${NEXT_PUBLIC_MOISSONNEUR_BAL_API_URL}
ENV NEXT_PUBLIC_API_SIGNALEMENT=${NEXT_PUBLIC_API_SIGNALEMENT}
ENV NEXT_PUBLIC_SOCIAL_NETWORKS_BLUESKY_KEY_DNS=${NEXT_PUBLIC_SOCIAL_NETWORKS_BLUESKY_KEY_DNS}

RUN npm i sharp

RUN npm run build

# Étape 2 : Image de production
FROM node:20.15.1-alpine

# Définit le répertoire de travail
WORKDIR /app

# Copie les fichiers nécessaires de l'étape de build
COPY --from=builder /app/package.json ./
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public

RUN mkdir -p /app/data && chown -R node:node /app/data

# Utilisation de l'utilisateur non-root
USER node

# Expose le port de l'application
EXPOSE 3000

# Commande de démarrage de l'application
CMD ["sh", "-c", "npm start"]
