services:
  frontend:
    build: 
      dockerfile: 'Dockerfile.dev'
    container_name: frontend
    volumes:
    - ./:/app
    - /app/node_modules
    - /app/.next
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
