version: '3.8'

services:
  frontend:
    build:
      dockerfile: "dockerfile.dev"
    container_name: frontend-new-site
    volumes:
      - ./public:/app/public
      - ./src:/app/src
      - ./next.config.mjs:/app/next.config.mjs
      - ./tsconfig.json:/app/tsconfig.json
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./.env:/app/.env
      - ./.env.default:/app/.env.default
      - ./.git:/app/.git
      - ./.next:/app/.next
      - ./.storybook:/app/.storybook
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_ADRESSE_URL=${NEXT_PUBLIC_ADRESSE_URL}
      - NEXT_PUBLIC_API_BAN_URL=${NEXT_PUBLIC_API_BAN_URL}
      # App Configuration
      - NEXT_PUBLIC_CERTIFICAT_NUMEROTATION_ENABLED=${NEXT_PUBLIC_CERTIFICAT_NUMEROTATION_ENABLED}
      - ENABLE_HELMET=${ENABLE_HELMET}
      # External URLs
      - NEXT_PUBLIC_API_GEO_URL=${NEXT_PUBLIC_API_GEO_URL}
      - NEXT_PUBLIC_API_ETABLISSEMENTS_PUBLIC=${NEXT_PUBLIC_API_ETABLISSEMENTS_PUBLIC}
      - NEXT_PUBLIC_DATAGOUV_URL=${NEXT_PUBLIC_DATAGOUV_URL}
      # API search for Addok Geocodeur
      - NEXT_PUBLIC_API_ADRESSE=${NEXT_PUBLIC_API_ADRESSE}
      - NEXT_LAST_UPDATED_DATE_ADDOCK_URL=${NEXT_LAST_UPDATED_DATE_ADDOCK_URL}
      # BAL - API Depot Access Configuration
      - NEXT_PUBLIC_API_DEPOT_URL=${NEXT_PUBLIC_API_DEPOT_URL}
      - API_DEPOT_TOKEN=${API_DEPOT_TOKEN}
      - SESSION_SECRET=${SESSION_SECRET}
      # Blog Configuration
      - NEXT_PUBLIC_GHOST_KEY=${GHOST_KEY}
      - NEXT_PUBLIC_GHOST_URL=${NEXT_PUBLIC_GHOST_URL}
      - NEXT_PUBLIC_GHOST_URL_IMAGES_SOURCE=${NEXT_PUBLIC_GHOST_URL_IMAGES_SOURCE}
      # BAL environements parameters
      - NEXT_PUBLIC_BAL_ADMIN_API_URL=${NEXT_PUBLIC_BAL_ADMIN_API_URL}
      - NEXT_PUBLIC_BAL_API_URL=${NEXT_PUBLIC_BAL_API_URL}
      - NEXT_PUBLIC_MOISSONNEUR_BAL_API_URL=${NEXT_PUBLIC_MOISSONNEUR_BAL_API_URL}
      - NEXT_PUBLIC_MES_ADRESSES=${NEXT_PUBLIC_MES_ADRESSES}
      - NEXT_PUBLIC_BAL_WIDGET_URL=${NEXT_PUBLIC_BAL_WIDGET_URL}
      - NEXT_PUBLIC_CLIENT_GUICHET_ADRESSE=${NEXT_PUBLIC_CLIENT_GUICHET_ADRESSE}
      - NEXT_PUBLIC_CLIENT_MES_ADRESSE=${NEXT_PUBLIC_CLIENT_MES_ADRESSE}
      - NEXT_PUBLIC_CLIENT_FORMULAIRE_PUBLICATION=${NEXT_PUBLIC_CLIENT_FORMULAIRE_PUBLICATION}
      # Matomo Configuration
      - NEXT_PUBLIC_MATOMO_URL=${NEXT_PUBLIC_MATOMO_URL}
      - NEXT_PUBLIC_MATOMO_SITE_ID=${NEXT_PUBLIC_MATOMO_SITE_ID}
      # S3 Configuration
      - S3_CONFIG_ACCESS_KEY_ID=${S3_CONFIG_ACCESS_KEY_ID}
      - S3_CONFIG_SECRET_ACCESS_KEY=${S3_CONFIG_SECRET_ACCESS_KEY}
      - S3_CONFIG_REGION=${S3_CONFIG_REGION}
      - S3_CONFIG_ENDPOINT=${S3_CONFIG_ENDPOINT}
      # Social Networks
      - NEXT_PUBLIC_SOCIAL_NETWORKS_URL_XCOM=${NEXT_PUBLIC_SOCIAL_NETWORKS_URL_XCOM}
      - NEXT_PUBLIC_SOCIAL_NETWORKS_URL_FACEBOOK=${NEXT_PUBLIC_SOCIAL_NETWORKS_URL_FACEBOOK}
      - NEXT_PUBLIC_SOCIAL_NETWORKS_URL_LINKEDIN=${NEXT_PUBLIC_SOCIAL_NETWORKS_URL_LINKEDIN}
      - NEXT_PUBLIC_SOCIAL_NETWORKS_URL_GITHUB=${NEXT_PUBLIC_SOCIAL_NETWORKS_URL_GITHUB}
      # Brevo
      - NEXT_PUBLIC_BREVO_API_URL=${NEXT_PUBLIC_BREVO_API_URL}
      - BREVO_API_KEY=${BREVO_API_KEY}
      # Altcha
      - NEXT_PUBLIC_ALTCHA_API_URL=${NEXT_PUBLIC_ALTCHA_API_URL}

