version: 2

defaults:
  workspace_root: &workspace_root
    ~/adressedatagouv

  container: &default_container
    working_directory: *workspace_root
    docker:
      - image: circleci/node:8

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  restore_node_modules: &restore_node_modules
    restore_cache:
      name: Restore node_modules cache
      keys:
        - v1-adressedatagouv-node-{{ checksum "yarn.lock" }}
        - v1-adressedatagouv-node-

jobs:
  checkout:
    <<: *default_container
    steps:
      - checkout

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - ./

  install:
    <<: *default_container
    steps:
      - *attach_workspace
      - *restore_node_modules

      - restore_cache:
          name: Restore yarn cache
          keys:
            - v1-adressedatagouv-yarn-{{ checksum "yarn.lock" }}
            - v1-adressedatagouv-yarn-

      - run:
          name: Install dependencies
          command: yarn

      - save_cache:
          name: Save yarn cache
          key: v1-adressedatagouv-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn/

      - save_cache:
          name: Save node_modules cache
          key: v1-adressedatagouv-node-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/

  lint:
    <<: *default_container
    steps:
      - *attach_workspace
      - *restore_node_modules

      - run:
          name: Lint JavaScript
          command: yarn lint

  build:
    <<: *default_container
    steps:
      - *attach_workspace
      - *restore_node_modules

      - run:
          name: Build output bundles
          command: yarn build

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .next/

workflows:
  version: 2

  build_test_deploy:
    jobs:
      - checkout

      - install:
          requires:
            - checkout

      - build:
          requires:
            - install

      - lint:
          requires:
            - install
